id = "dark-green-jungle-theme"
name = "Dark Green Jungle"
schema_version = 1
version = "0.0.1"
authors = ["AaBbdev29"]
description = "a Relax theme  with dark green jungle color and green palette"
repository = "https://github.com/TalalMash/Dark-Green-Jungle-Zed-Fork"
themes = ["themes/dark-green-jungle.json"]
